version: '3'
services:
  cypress:
    container_name: local_cypress
    build: ./docker/dockerFiles/cypress
    working_dir: /docker/test/cypress
    tty: true
    volumes:
      - ./:/docker
      - ./containers/cypress/:/containers

  testcafe:
    container_name: local_testcafe
    build: ./docker/dockerFiles/testcafe
    working_dir: /docker/test/testcafe
    tty: true
    volumes:
      - ./:/docker
      - ./containers/testcafe/:/containers
